### PR TITLE
Add run on repl.it badge

### PR DESCRIPTION
**Pull request by amasad**
Uni seems really cool, it's useful enough to want to run it in the browser too. This adds a "run on repl.it" badge that lets people play around and tinker with the tool on the web. You can try it yourself here: https://repl.it/@amasad/uni

Here is how it looks like:
Screen Shot 2019-12-12 at 3 51 09 PM

### CODE REVIEW

**Comment by arp242** [comment]
Thanks!

Will this automatically get updated to the latest release? Or how does that work?

**Comment by amasad** [comment]
It's operating on the master branch. I.e. Everytime someone clicks the badge it's cloning a fresh one.

**Comment by arp242** [comment]
Thanks. I played around with it a bit, and to be honest I find the UI a bit confusing to give people a quick in-browser demo. Instead  I played around with wasm a bit today and thay seems to work quite well, so I think I'll use that instead. See #9

**Comment by amasad** [comment]
I work on repl.it -- can you give me some feedback as to what's confusing
about this? Even if you don't want to use it it'll be useful to know and
potentially fix.

**Pull request closed without merging**
